### ISSUE TITLE
TypeError: Cannot read property 'ended' of undefined

### ISSUE THREAD

**Issue by amir20** [mcollina/split2#10]
I am using this module and I consistently get this error. 

```
 if (state.ended) writeAfterEnd(this, cb);else if (validChunk(this, state, chunk, cb)) {
           ^

TypeError: Cannot read property 'ended' of undefined
    at DestroyableTransform.Object.<anonymous>.Writable.write (/phantomjs-node/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:12)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
npm ERR! Test failed.  See above for more details.
```

I haven't found any other issues similar to this. Does anybody have any idea what is going on? 

Also related to https://github.com/rvagg/through2/issues/77#issuecomment-263136472

**Comment by mcollina** [comment]
which version of node/split2/readable-stream are you using? Can you please upload a full example that triggers you error? It works fine over here.

**Comment by amir20** [comment]
Let's see:

- `node -v`:  7.2.0
- `npm ls split2`: split2@2.1.0
- `yarn ls`: [here](https://gist.github.com/anonymous/ce472ae25dd48ab46ed0767118572132) 


Code is located at https://github.com/amir20/phantomjs-node/tree/split2 and you can get this exception by doing `npm test -- lib/__test__/phantom.spec.js`.

I am trying to isolate the problem so that I can just produce it with a stream. I can try to do that tomorrow if that is helpful. 

Currently, [master](https://github.com/amir20/phantomjs-node/blob/master/package.json#L29) is using split v1. 

I'd like to use split2 but I can't figure out what is throwing this error. 

Last thing -- you can do `DEBUG=true npm test -- lib/__test__/phantom.spec.js` to see what is actually happening with the streams. 

I see

```
debug: Starting /usr/local/bin/phantomjs /Users/amirraminfar/Workspace/phantomjs-node/lib/shim/index.js
debug: Sending: {"id":"dcbwil.fyxw7i0h33di1fba028.0fkkczt1emif8wexn.f9njg0c0udi1130fk8.nwivgarwwmi","target":"phantom","name":"createPage","params":[],"deferred":null}
debug: Sending: {"id":"wj3txn.5p9q1rod2t91krhnhz.jq0ngbvs4io7wf7k.7qxfbfq1tt9e9inrf.dscyxzcfecdi","target":"phantom","name":"createPage","params":[],"deferred":null}

 RUNS  lib/__test__/phantom.spec.js
/Users/amirraminfar/Workspace/phantomjs-node/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239
  if (state.ended) writeAfterEnd(this, cb);else if (validChunk(this, state, chunk, cb)) {
           ^

```

There is nothing special about that last line. 

Let me know what else I can do to provide help. As a project maintainer myself, I know it's sometimes how to debug these issues.

**Comment by mcollina** [comment]
There is almost no difference in the streams related cose between split v1 and split v2.
The problem might be somewhere else: yarn or maybe phantom.

Out of curiosity, does all of that works with an install done through plain npm, with node v6?

**Comment by amir20** [comment]
> There is almost no difference in the streams related cose between split v1 and split v2.
The problem might be somewhere else: yarn or maybe phantom.

The only thing I am changing is split versions though. 

> Out of curiosity, does all of that works with an install done through plain npm, with node v6?

```
$ rm -rf node_modules/
$ node -v
# v6.9.1
$ npm i
# ...
$ npm test -- lib/__test__/phantom.spec.js
> phantom@3.1.0 pretest /Users/amirraminfar/Workspace/phantomjs-node
> gulp build:test

[22:26:22] Requiring external module babel-register
[22:26:22] Using gulpfile ~/Workspace/phantomjs-node/gulpfile.babel.js
[22:26:22] Starting 'build'...
[22:26:22] Starting 'copy-snapshots'...
[22:26:22] Finished 'copy-snapshots' after 34 ms
[22:26:22] Finished 'build' after 64 ms
[22:26:22] Starting 'build:test'...
[22:26:22] Finished 'build:test' after 33 μs

> phantom@3.1.0 test /Users/amirraminfar/Workspace/phantomjs-node
> npm run lint && jest "lib/__test__/phantom.spec.js"


> phantom@3.1.0 lint /Users/amirraminfar/Workspace/phantomjs-node
> eslint . && flow check

Found 0 errors

 RUNS  lib/__test__/phantom.spec.js

/Users/amirraminfar/Workspace/phantomjs-node/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:272
  if (state.ended) writeAfterEnd(this, cb);else if (validChunk(this, state, chunk, cb)) {
           ^
TypeError: Cannot read property 'ended' of undefined
    at DestroyableTransform.Object.<anonymous>.Writable.write (/Users/amirraminfar/Workspace/phantomjs-node/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:272:12)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:548:20)
npm ERR! Test failed.  See above for more details.
```

Same error. 

I think next step is to emulate all of the data in streams in a test without phantomjs to help us understand. Otherwise, there isn't any differences between master and split2 branch.

**Comment by mcollina** [comment]
I investigated this a bit. Unfortunately I have no time to dedicate to it further.

Some facts:

a) split2 works on Node v0.10 to v7 (just tested)
b) the project uses some heavy transpilation, making it hard to understand why part of the stream API is not lifted correctly, or what the actual problem is.
c) I understood split2 v1 vs split2 v2, while you move from split to split2. The main difference is that split uses Node v0.8 API for streams, while split2 use Node v0.10+ API for streams. It seems like this is run on node v0.8 or similar.

I am sure this is a bug somewhere else and not here. If you find it's here, feel free to send a PR.

**Comment by amir20** [comment]
Could you please reopen the ticket at least? Closing it with no time to investigate seems a little quick. I can get you a small example of how this breaks and remove all the transpilations as I suggested above. We should do that before closing the ticket. If I can't code to reproduce it then I will close it.

**Comment by amir20** [comment]
I am losing my mind. I was able to see what phantom produces

> >{"target":"phantom","name":"invokeMethod","params":["exit"],"deferred":null,"id":"c1e5fd516a9047238a98c65a1bef4cf9"}>{"target":"phantom","name":"createPage","params":[],"deferred":null,"id":"029ae1490e44399e097ff7fac253d1d7","response":{"pageId":"029ae1490e44399e097ff7fac253d1d7"}}

But I can't get to throw same error with 

```js
const fs = require('fs');
const split2 = require('split2');


fs.createReadStream('mocked.out')
    .pipe(split2())
    .on('data', function(line) {
        console.log(line);
    });
```

So I am giving up right now. I'll have to stick with `split` until I figure out what is going on. Thanks for playing along.
