### ISSUE TITLE
Optional color support

### ISSUE THREAD

**Issue by hackwaly** [mcollina/split2#31]
The prefix is added to each line of line stream created by split2. But it's color is incorrect.

![image](https://user-images.githubusercontent.com/540298/71527947-8412cd00-2918-11ea-859a-773a94935326.png)

If split2 can provide an option to do color-aware split. The issue in above image can be solved with zero effort.

**Comment by mcollina** [comment]
This module does not add any prefix. I think what is happening is that color is started on one line, and not closed when it’s wrapped. I think implementing this behavior is outside of the scope of this module, and  be implemented on top of it (as part of the mapper function). I would recommend to create a new module that wraps this one.
