### ISSUE TITLE
Odd result when using grouping in an regex

### ISSUE THREAD

**Issue by theasp** [mcollina/split2#32]
Hi, I'm trying to use a grouping in a regex so that the record separator is included in the first chunk, but it seems to be putting it in it's own chunk.  Is this the expected behaviour?

For example, this test case fails:
```javascript
test('split using a custom regexp matcher and group', function (t) {
  t.plan(2)

  var input = split(/(~)/)            

  input.pipe(strcb(function (err, list) {
    t.error(err)
    t.deepEqual(list, ['hello~', 'world'])
  }))

  input.end('hello~world')
})
```

```
    not ok 2 - should be equivalent
      ---
      found:
        - hello
        - '~'
        - world
      wanted:
        - hello~
        - world
```

**Comment by mcollina** [comment]
That is on purpose and it matches the behavior of string.split(regexp).

**Comment by IronSavior** [comment]
Use a zero-width pattern that matches the space after the separator.

**Comment by theasp** [comment]
Thank you!  A look behind works perfectly.
