### ISSUE TITLE
Publish a New Release to NPM

### ISSUE THREAD

**Issue by tomergg** [mcollina/split2#37]

**Comment by mcollina** [comment]
why?

**Comment by tomergg** [comment]
Why not?

Seems like there are new versions, with dependency updates, that have not been published in the past year.
Mainly the `readable-stream` v3 update.

Thank you.

**Comment by mcollina** [comment]
I’m unsure where you are getting your data from, but latest versions is 3.1.1, which has all the things you are mentioning.

What has not been released are only devDep updates.
