### ISSUE TITLE
include "typings" field in package.json

### ISSUE THREAD

**Issue by rolandjitsu** [mcollina/split2#4]
Now that the TS compiler supports module [resolution](https://github.com/Microsoft/TypeScript/issues/2338) via node, it would be nice not to use TSD to install the typing but instead have them included with the npm package.

**Comment by mcollina** [comment]
I'm not getting what should I do. If you would like to send a PR, I'll have a look!

**Comment by rolandjitsu** [comment]
Well, for those of use that use TypeScript to write node apps, when we import something we need to add some typings that describe the internals of the library. For most of those, someone has already written some typings definitions available at TSD. But now that is not necessary as the TS compiler has a new feature where you can resolve those definitions directly from `node_modules`.

I am not sure what the best way to do it would be as there are a few ways as described [here](https://github.com/Microsoft/TypeScript/issues/2338). I hope I made it more clear now.

**Comment by mcollina** [comment]
Unfortunately I have no time to implement this myself. However, I'd be happy to accept a PR on this regard.

**Comment by rolandjitsu** [comment]
Ok, I'll give it a try :)

**Comment by mcollina** [comment]
Closing as there was no acitivity for close to 2 years.
