### ISSUE TITLE
Do we have to manually destroy split2 stream?

### ISSUE THREAD

**Issue by sergiz** [mcollina/split2#47]
Hello.

I was wondering, do we have to manually destroy every split2 transform stream? When the stream that pipes into split2 is destroyed, split2 "close" event is not emitted (only "end" is). I'm using node v14, so autoDestroy defaults to true.

**Comment by mcollina** [comment]
Could you please provide a full example to reproduce?

**Comment by sergiz** [comment]
```js
const fs = require('fs');
const split2 = require('split2');

const file = fs.createReadStream('./node memuse.txt');

file
  .on('end', () => {
    console.log('file ended');
  })
  .on('close', () => {
    console.log('file closed');
  });

file.pipe(split2())
  .on('data', (line) => {
    console.log('line: ' + line);
  })
  .on('end', () => {
    console.log('split ended');
  })
  .on('close', () => {
    console.log('split closed');
  });
```

The output is:

> file ended
> split ended
> file closed

**Comment by sergiz** [comment]
```js
const fs = require('fs');
const split2 = require('split2');

const file = fs.createReadStream('./file.txt');

file
  .on('end', () => {
    console.log('file ended');
  })
  .on('close', () => {
    console.log('file closed');
  });

file.pipe(split2())
  .on('data', (line) => {
    console.log('line: ' + line);
  })
  .on('end', () => {
    console.log('split ended');
  })
  .on('close', () => {
    console.log('split closed');
  });
```

The output is:

> file ended
> split ended
> file closed

**Comment by mcollina** [comment]
You should use `pipeline` or `pump` to pipe things together and handle all cases.

**Comment by sergiz** [comment]
Thanks for these suggestions. However, I don't have any use for split2 "close" event. I was only wondering whether transform stream stays alive forever if you do not manually destroy it, leading to a memory leak.

**Comment by sergiz** [comment]
@mcollina, so is it a memory leak if you don't manually destroy split2 stream before letting it out of reach?

**Comment by mcollina** [comment]
No, everything gets collected.
