### ISSUE TITLE
[question] reading line by line in reverse order 

### ISSUE THREAD

**Issue by mariusa** [mcollina/split2#54]
Hi,

(asking here since Discussions aren't enabled)
Could `split2` be used to help reading a file (remote `https://a.com/file.txt` or on local disk) line by line in reverse order?

Example remote file:
```
line 1
long line 2
line 3
long line 4
another line 5
```

Looking to read in reverse **line** order (not character order)
```
another line 5
long line 4
line 3
long line 2
line 1
```

One solution would be to 
1. use `split2` to determine offsets of the line breaks. It would use the received line of text just to save line length, and discard the actual content.
2. use https://nodejs.org/api/fs.html#fscreatereadstreampath-options with `start/end` arguments from offsets to read each line in reverse

Would you have any suggestions on other ways, please?

Thanks!

**Comment by mcollina** [comment]
Unfortunately this is not supported and out of scope, you'd need to develop a separate module.
