### ISSUE TITLE
if `Buffer#toString` not consume all bytes?

### ISSUE THREAD

**Issue by heroboy** [mcollina/split2#6]
If i write data one byte by one byte, it emit empty.
```
var split = require("split2");
var buf = new Buffer("烫烫烫\r\n锟斤拷", "utf8");
var s = split();
s.on("data", function (data) { 
	console.log(data);
});

for (var i = 0; i < buf.length; ++i)
{
	s.write(buf.slice(i, i + 1));
}
s.end();
```

**Comment by mcollina** [comment]
It works fine for me.

I've also checked:
```js
var split = require("split2");
var buf = new Buffer("aa\r\nbbb", "utf8");
var s = split();
s.on("data", function (data) {
    console.log(data);
});

for (var i = 0; i < buf.length; ++i)
{
    s.write(buf.slice(i, i + 1));
}
s.end();
```

Which version of node are you using?

**Comment by heroboy** [comment]
no, you should not use string like "aaabbb".
You should use strings that string.length not equals to buffer.length .
For example, `"烫"` buffer in utf8 is `[0xe7,0x83,0xab]`, in above code it will get three chunks in transform function,none of the three chunks can be converted to `"烫"`.

**Comment by mcollina** [comment]
I'm lost. I think the best way is for you to send a PR with a valid unit test and possibly a fix.

It is working for me as far as I know: https://github.com/mcollina/split2/blob/master/test.js#L211-L221

**Comment by heroboy** [comment]
change
```
input.end("烫烫烫\r\n锟斤拷")
```
to
```
var buf = new Buffer("烫烫烫\r\n锟斤拷", "utf8");
for (var i = 0; i < buf.length; ++i)
{
	input.write(buf.slice(i, i + 1));
}
input.end();
```

**Comment by mcollina** [comment]
Confirmed, I'll see how it is fixable.

**Comment by heroboy** [comment]
try this
```
through({encoding:"utf8"})                 //convert Buffer to String (buf => data)
    .pipe(through({decodeStrings:false},   //prevent convert String to Buffer (buf => chunk)
        function(chunk,enc,cb){}           //your transform function,now chunk is string.
);
```
And please expose the encoding in options.
